version: "3.3"
services: 
    server:
        build: 
            context: "server"
            dockerfile: Dockerfile.dev
        ports:
            - "5000:8000"
        volumes:
            - ./server/.:/usr/app
        env_file: .env

    mongo:    
        image: mongo:${MONGO_IMAGE_VERSION}
        restart: always
        ports: 
            - "${MONGO_OUTER_PORT}:${MONGO_INNER_PORT}"
        volumes:
            - ./mongodb/data:/data/db
            - ./mongodb/mongod.conf:/etc/mongo/mongod.conf
    
    mongo-express:
        image: mongo-express:${MONGO_EXPRESS_IMAGE_VERSION}
        restart: always    
        ports:
            - "${MONGO_EXPRESS_PORT}:8081"


